#======================================================================#
#----------------Configuration File for Spectral Analysis--------------#
#----------------------------------------------------------------------#
#
#
# This file incorporates all configuration parameters for the following scripts:
# map_eval.py
# 
# Please keep in mind, that all Kommas in Map-Data have to be converted to dots.
# Example: 12,234235 -> 12.234235

map_paras:
        file: "DCmap_hBN-WS2-hBN_4K_100uW_532nm_50x50x10s-50x50V.txt"
        dimensions: 50
        background: 98

