#======================================================================#
#----------------Configuration File for Spectral Analysis--------------#
#----------------------------------------------------------------------#
#
#
# This file incorporates all configuration parameters for the following scripts:
# map_eval.py
# 
# Please keep in mind, that all Kommas in Map-Data have to be converted to dots.
# Example: 12,234235 -> 12.234235

# -- Experimental Parameters
# these include all quantities and qualities, universal and equal in all datasets
# All manipulations and evaluations use the target_path while the data is fetched
# from the source_path but not altered there. 
 
general:
        source_path: "V:\\temp\\Foerste\\Auswertungen\\2018-02-09-WS2-MonolayerBilayer-GateControl-Mithrandir\\Raw_Data\\"
        working_dir: "V:\\temp\\Foerste\\Auswertungen\\2018-02-09-WS2-MonolayerBilayer-GateControl-Mithrandir\\Evaluation\\"
        background: 0 #Counts
        laser: "WLS"
        objective: "unknown"
        setup: "confocal"
        excitation: #530
        bandwidth: #10
        repetition: #78 #MHz
        temperature: 4 #K
        power: #10 #mW
#Map-Evaluation

map_paras:
        file: "WS2-PLMap-8s-25-25um-03um_step_550+-5nm_80uW.tsv.mat"
        calibration_file: "WS2-ML-enc-20s--10-+15V-550+-5nm-01test.wlen_to_px.tsv.gz"
        dimensions: 80
        background: 0

sweep_paras:
        file: "homo-Refl-1s-+-32V.Voltage_Sweep.tsv.gz"
        calibration_wavelength: "lower_middle_061217_20s.wlen_to_px.tsv.gz"
        calibration_parameter: "lower_middle_061217_20s.voltages.tsv.gz"
        background_file: "Background-4K.csv"

auto_paras:
        use_auto: 'TRUE'
        erase_cosmics: 'TRUE'
        cosmic_factor: 5 #point has to be 10x its neighbours
        cosmic_distance: 7 #distance of the neighbours
        cosmic_cycles: 7 # number of checks

spec_paras: #Boolean paramenters checked from top -> bottom. Checked for 'TRUE'
        seperator: ' ' #seperator, that will be inserted by pretreatment.py
        convert_to_energy: 'TRUE'
        normalize: 'FALSE'
        convert_to_rate: 'TRUE'
        exposure: -1 #300 #seconds -- automatically checked
        background: 98

reference:
        offset: 0.017
        use: "TRUE"
        ref_name: "Toulouse"
        plot_name: "homemade"
        name: "Reference-WS2.txt"        
